"""add avatar_url to users table

Revision ID: 24cdbeaedc98
Revises: 464d39fc161a
Create Date: 2026-04-13 13:04:23.044201

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24cdbeaedc98"
down_revision: Union[str, Sequence[str], None] = "464d39fc161a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
