"""add image_url to feedbacks table

Revision ID: 464d39fc161a
Revises: ef8e2f530cc7
Create Date: 2026-04-11 18:43:29.294771

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "464d39fc161a"
down_revision: Union[str, Sequence[str], None] = "ef8e2f530cc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("system_feedbacks", sa.Column("image_url", sa.Text(), nullable=True))
    op.alter_column(
        "system_feedbacks", "status", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "system_feedbacks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_feedbacks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "system_feedbacks", "status", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("system_feedbacks", "image_url")
    # ### end Alembic commands ###
