"""make card holder nullable and add description

Revision ID: 4d8e5fb127eb
Revises: 4b9b9509abbe
Create Date: 2026-04-08 14:10:39.793691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d8e5fb127eb"
down_revision: Union[str, Sequence[str], None] = "4b9b9509abbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "holder_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("cards", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "description")
    # ### end Alembic commands ###
