"""add totp_secret

Revision ID: 81b3acb7faeb
Revises: 24cdbeaedc98
Create Date: 2026-04-13 14:37:00.905926

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81b3acb7faeb"
down_revision: Union[str, Sequence[str], None] = "24cdbeaedc98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_secret", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
