"""add cpf to users

Revision ID: a479a3d2483d
Revises: f7620ded9ddb
Create Date: 2026-05-02 23:57:55.014708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a479a3d2483d"
down_revision: Union[str, Sequence[str], None] = "f7620ded9ddb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("cpf", sa.String(length=11), nullable=True))
    op.create_unique_constraint("users_cpf_key", "users", ["cpf"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_cpf_key", "users", type_="unique")
    op.drop_column("users", "cpf")
    # ### end Alembic commands ###
