"""remove unique cpf on card_holders

Revision ID: b3e47f61c707
Revises: a479a3d2483d
Create Date: 2026-05-03 01:11:02.748615

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3e47f61c707"
down_revision: Union[str, Sequence[str], None] = "a479a3d2483d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("card_holders_cpf_key"), "card_holders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("card_holders_cpf_key"),
        "card_holders",
        ["cpf"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
